### PR TITLE
Remove Nth Node From End of List.cpp

### PR DESCRIPTION
**Pull request by RajivMishra02**
Remove Nth Node From End of List.cpp

### CODE REVIEW

**Comment by Navaneethp007** [comment]
@RajivMishra02 do check on the code you have submitted.There is errors in it. Correct the errors and create a pr again
keep contributing!!!!

**Comment by RajivMishra02** [comment]
Thank you for your email, I have deleted the pull request for the same and
will look into the matter and get back to you, can you please merge the 3rd
Problem Solution into the main.

**Comment by Navaneethp007** [comment]
I think I have merged your other pr

**Comment by Navaneethp007** [comment]
If you still find no errors in the code....just reopen this pr and let me know

**Comment by RajivMishra02** [comment]
Yes, it’s absolutely fine. I have submitted another pull request for a
different question I had solved on LeetCode.

**Comment by RajivMishra02** [comment]
Hey!! Can you merge my last PR to main to complete my 4 PRs in total. You
have merged three of mine, and only one is left.

**Pull request closed without merging**
